" .vimrc
" Author: Mark Nichols <mark@zanshin.net>
" Source: http://github.com/zanshin/dotfiles/vim/vimrc
"

" Forget compatibility with vi. Who cares.
set nocompatible

set laststatus=2                  " always show the status line
set cmdheight=2                   " and use a two-line tall status line
set showcmd                       " show the command
" set noshowmode                    " don't show the mode, vim-airline will do that for us
set autoindent                    " turns it on
set smartindent                   " does the right thing (mostly) in programs
set linespace=3                   " prefer a slight higher line height
set linebreak                     " wrap intelligently, won't insert hard line breaks
set wrap                          " use line wrapping
set textwidth=79                  " at column 79
set ruler                         " display current cursor position
set list                          " show invisible characters
set listchars=tab:▸\ ,eol:¬,trail:⋅,nbsp:␣,extends:❯,precedes:❮
set showmatch                     " show matching brackets
if exists("&relativenumber")
  set relativenumber              " use relative line numbers
endif
set number                        " except for the current line - absolute number there
set backspace=indent,eol,start    " make backspace behave in a sane manner
set mousehide                     " hide mouse when typing
set foldenable                    " enable code folding
set history=1000
set ffs=unix,mac,dos              " default file types
set autoread                      " automatically update file when editted outside of vim
set cryptmethod=blowfish          " Strong encryption is good

" Folding settings
set foldcolumn=3                  " room for fold markers
set foldmethod=marker             " use the standard 3 curly braces as markers

" Encoding anyone?
set termencoding=utf-8            " we like utf-8
set encoding=utf-8

" Setup automatic text formatting/wrapping (previously: grn1 )
set formatoptions=
set formatoptions-=t              " don't autowrap text
set formatoptions+=c              " do autowrap comments
set formatoptions+=r              " automatically continue comments
set formatoptions+=o              " automatically continue comments when hitting 'o' or 'O'
set formatoptions+=q              " allow formating of comments with 'gq'
set formatoptions+=n              " recognize numbered lists
set formatoptions+=l              " don't break long lines that were already there

" What to do with files and focus
set autowrite           " write out old file when switching between files
set autoread            " reload files changed on disk, i.e. via `git checkout`
au FocusLost * :wa      " save file when Vim loses focus
set hidden              " switch beteen buffers without saving

set backup                       " emable backups
set noswapfile                    " It's the 21st century already

set undodir=~/.vim/tmp/undo//     " undo files
set backupdir=~/.vim/tmp/backup// " backups
set directory=~/.vim/tmp/swap     " swap files

set tabstop=4           " 2 spaces for a tab
set shiftwidth=4        " 2 spaces for autoindenting
set softtabstop=4       " when <BS>, pretend a tab is removed even if spaces
set expandtab           " expand tabs to spaces (overloadable by file type)

" Sudo to write
cmap w!! w !sudo tee % >/dev/null

if has('syntax') && !exists('g:syntax_on')
  syntax on
endif